// <auto-generated />
using System;
using Delivery.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Delivery.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200421062521_seagregorestriccionalacampoplaca")]
    partial class seagregorestriccionalacampoplaca
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Delivery.Web.Data.Entities.DetalleViajeEntity", b =>
                {
                    b.Property<int>("IdDetalleViaje")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha");

                    b.Property<double>("Latitud");

                    b.Property<double>("Longitud");

                    b.Property<int?>("ViajeIdViaje");

                    b.HasKey("IdDetalleViaje");

                    b.HasIndex("ViajeIdViaje");

                    b.ToTable("DetalleViajes");
                });

            modelBuilder.Entity("Delivery.Web.Data.Entities.RepartidorEntity", b =>
                {
                    b.Property<int>("IdRepartidor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.HasKey("IdRepartidor");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Repartidores");
                });

            modelBuilder.Entity("Delivery.Web.Data.Entities.ViajeEntity", b =>
                {
                    b.Property<int>("IdViaje")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Calificacion");

                    b.Property<string>("Comentarios");

                    b.Property<string>("Destino")
                        .HasMaxLength(100);

                    b.Property<double>("DestinoLatitud");

                    b.Property<double>("DestinoLongitud");

                    b.Property<DateTime?>("FechaFin");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<string>("Origen")
                        .HasMaxLength(100);

                    b.Property<double>("OrigenLatitud");

                    b.Property<double>("OrigenLongitud");

                    b.Property<int?>("RepartidorIdRepartidor");

                    b.HasKey("IdViaje");

                    b.HasIndex("RepartidorIdRepartidor");

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("Delivery.Web.Data.Entities.DetalleViajeEntity", b =>
                {
                    b.HasOne("Delivery.Web.Data.Entities.ViajeEntity", "Viaje")
                        .WithMany("DetalleViajes")
                        .HasForeignKey("ViajeIdViaje");
                });

            modelBuilder.Entity("Delivery.Web.Data.Entities.ViajeEntity", b =>
                {
                    b.HasOne("Delivery.Web.Data.Entities.RepartidorEntity", "Repartidor")
                        .WithMany("Viajes")
                        .HasForeignKey("RepartidorIdRepartidor");
                });
#pragma warning restore 612, 618
        }
    }
}
